### ISSUE TITLE
Update docs to mention how to work around Firestorm proxy issues

### ISSUE THREAD

**Issue by SaladDais** [SaladDais/Hippolyzer#25]
Firestorm didn't pull https://bitbucket.org/lindenlab/viewer/commits/454c7f4543688126b2fa5c0560710f5a1733702e into their latest release, so manually specifying a proxy is broken. Mention LinHippoAutoProxy or the debug settings or something. I don't particularly care about CEF / Dullahan proxy support.

**Comment by gwigz** [comment]
If it helps,

- **HttpProxyType** Web
- **BrowserProxyAddress** 127.0.0.1
- **BrowserProxyEnabled** TRUE
- **BrowserProxyPort** 9062
- **Socks5ProxyEnabled** TRUE
- **Socks5ProxyHost** 127.0.0.1
- **Socks5ProxyPort** 9062

**Comment by SaladDais** [comment]
Thanks! Put that in as workaround instructions, modern OS X safeguards against dylib injection means LinHippoAutoProxy would be annoying to use there even if explicit OS X support was added.
